server:
  port: 8084
spring:
  application:
    name: "ms-products"
  webflux:
    base-path: "/ms-products"
  devtools:
    add-properties: false
    restart:
      enabled: false
  profiles:
    active: "local"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
adapters:
  r2dbc:
    host: localhost
    port: 5435
    database: repu
    schema: repu
    username: admin
    password: "adm1n123@"
cors:
  #allowed-origins: "http://localhost:4200,http://localhost:8080"
  allowed-origins: "*"
security:
  jwt:
    # Esta es una llave de ejemplo en Base64 (32 bytes / 256 bits).
    secret: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"
logging:
  level:
    org.springframework.security: INFO
    org.springframework.web.reactive.function.server: INFO
