dependencies {
    implementation project(':model')
    implementation 'org.springframework:spring-context'
    implementation 'org.springframework.boot:spring-boot-starter-data-r2dbc'
    implementation 'org.postgresql:r2dbc-postgresql'
    implementation 'org.postgresql:r2dbc-postgresql'
    implementation 'org.reactivecommons.utils:object-mapper-api:0.1.0'
    implementation 'com.fasterxml.jackson.core:jackson-databind'

    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
    testImplementation 'org.reactivecommons.utils:object-mapper:0.1.0'
    implementation 'com.github.f4b6a3:uuid-creator:6.0.0'
}

