dependencies {
    implementation project(':model')
    implementation 'org.springframework:spring-context'
    implementation("org.springframework.security:spring-security-crypto:7.0.0")
    // JWT
    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'
}
